name: penhas
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.0+59
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.2
  cpfcnpj:
    git:
      url: https://github.com/erickhaendel/dart-cpfcnpj.git
      ref: "6258774d3de58ee9122f2b6047ebb0c5b833df19"
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/uSlashVlad/data_connection_checker.git
      ref: "1b983aa377d9984ab18292d5ff33768e284e93d6"
  device_info: ^2.0.3
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  flutter_mobx: ^2.0.2
  flutter_modular:
    git:
      url: https://github.com/pedrox-hs/modular.git
      path: flutter_modular
      ref: improvements
  flutter_phone_direct_caller: ^2.1.0
  flutter_sound: ^9.2.13
  flutter_svg: ^1.0.3
  flutter_tags:
    git:
      url: https://github.com/pedrox-hs/flutter_tags.git
      ref: null-safety
  flutter_widget_from_html: ^0.8.3+1
  freezed_annotation: ^1.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.1
  map_launcher: ^2.1.1
  mask_text_input_formatter: ^2.0.0
  mobx: ^2.0.5
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  smooth_star_rating:
    git:
      url: https://github.com/bhavin-concetto/smoothratingbar.git
      ref: "eb02312f9adc6a40e2488050fb2e58852a163bb8"
  timeago: ^3.1.0
  url_launcher: ^6.1.7
  uuid: ^3.0.5
  webview_flutter: ^3.0.0
  collection: ^1.15.0
  asuka: ^2.0.1+3
  stack_trace: ^1.10.0
  logging: ^1.0.2
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.7.0
  crypto: ^3.0.1
  http_parser: ^4.0.0
  logger: ^1.1.0
  scroll_to_index: ^2.1.1
  flutter_secure_storage: ^6.1.0
  synchronized: ^3.0.0+3

dependency_overrides:
  flutter_modular:
    git:
      url: https://github.com/pedrox-hs/modular.git
      path: flutter_modular
      ref: improvements

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_modular_test:
    git:
      url: https://github.com/pedrox-hs/modular.git
      path: flutter_modular_test
      ref: improvements
  flutter_launcher_icons: ^0.9.2
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "cd516a8e7483bfc7971ec9ac8f2d589e68247441"
  freezed: ^1.1.0
  mobx_codegen: ^2.0.4
  mockito: 5.0.16
  lint: ^1.8.1
  mocktail: ^0.3.0
  flutter_lints: ^1.0.4
  plugin_platform_interface: ^2.0.0
  geolocator_platform_interface: ^4.0.3

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/icon/icon.png'

flutter_launcher_name:
  name: 'PenhaS'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/penhas_symbol/penhas_symbol.png
    - assets/images/stealth_mode_tutorial_image_1/stealth_mode_tutorial_image_1.png
    - assets/images/stealth_mode_tutorial_image_2/stealth_mode_tutorial_image_2.png
    - assets/images/stealth_mode_tutorial_image_3/stealth_mode_tutorial_image_3.jpg
    - assets/images/stealth_mode_tutorial_image_4/stealth_mode_tutorial_image_4.png
    - assets/images/svg/drawer/account_setting.svg
    - assets/images/svg/drawer/trash.svg
    - assets/images/svg/drawer/user_profile.svg
    - assets/images/svg/bottom_bar/chat.svg
    - assets/images/svg/bottom_bar/chat_selected.svg
    - assets/images/svg/bottom_bar/compose_tweet.svg
    - assets/images/svg/bottom_bar/compose_tweet_selected.svg
    - assets/images/svg/bottom_bar/emergency_controll.svg
    - assets/images/svg/bottom_bar/feed.svg
    - assets/images/svg/bottom_bar/feed_selected.svg
    - assets/images/svg/bottom_bar/support_point.svg
    - assets/images/svg/bottom_bar/support_point_selected.svg
    - assets/images/svg/tweet_action/tweet_action_block.svg
    - assets/images/svg/tweet_action/tweet_action_chat.svg
    - assets/images/svg/tweet_action/tweet_action_delete.svg
    - assets/images/svg/tweet_action/tweet_action_report.svg
    - assets/images/svg/reset_password/recovery_password_step_1.svg
    - assets/images/svg/reset_password/recovery_password_step_2.svg
    - assets/images/svg/reset_password/recovery_password_step_3.svg
    - assets/images/svg/help_center/help_center_call_police.svg
    - assets/images/svg/help_center/help_center_guardian.svg
    - assets/images/svg/help_center/help_center_record.svg
    - assets/images/svg/tutorial/tutorial_guardian_01.svg
    - assets/images/tutorial_guardian_2/tutorial_guardian_2.png
    - assets/images/tutorial_guardian_3/tutorial_guardian_3.png
    - assets/images/tutorial_record_1/tutorial_record_1.png
    - assets/images/tutorial_record_2/tutorial_record_2.png
    - assets/images/tutorial_record_4/tutorial_record_4.png
    - assets/images/svg/help_center/guardians/guardians_delete.svg
    - assets/images/svg/help_center/guardians/guardians_edit.svg
    - assets/images/svg/help_center/guardians/guardians_sent_invite.svg
    - assets/images/svg/help_center/guardians/guardians_alert.svg
    # Zodiac
    - assets/images/zodiac/svg/constelation_aquarius.svg
    - assets/images/zodiac/svg/constelation_aries.svg
    - assets/images/zodiac/svg/constelation_cancer.svg
    - assets/images/zodiac/svg/constelation_capricorn.svg
    - assets/images/zodiac/svg/constelation_gemini.svg
    - assets/images/zodiac/svg/constelation_leo.svg
    - assets/images/zodiac/svg/constelation_libra.svg
    - assets/images/zodiac/svg/constelation_pisces.svg
    - assets/images/zodiac/svg/constelation_sagittarius.svg
    - assets/images/zodiac/svg/constelation_scorpio.svg
    - assets/images/zodiac/svg/constelation_taurus.svg
    - assets/images/zodiac/svg/constelation_virgo.svg
    - assets/images/zodiac/svg/moon.svg
    - assets/images/zodiac/svg/sun.svg
    - assets/images/zodiac/svg/venus.svg
    - assets/images/zodiac/icon_aquarius/aquarius.png
    - assets/images/zodiac/icon_aries/aries.png
    - assets/images/zodiac/icon_cancer/cancer.png
    - assets/images/zodiac/icon_capricorn/capricorn.png
    - assets/images/zodiac/icon_gemini/gemini.png
    - assets/images/zodiac/icon_leo/leo.png
    - assets/images/zodiac/icon_libra/libra.png
    - assets/images/zodiac/icon_pisces/pisces.png
    - assets/images/zodiac/icon_sagittarius/sagittarius.png
    - assets/images/zodiac/icon_scorpio/scorpio.png
    - assets/images/zodiac/icon_taurus/taurus.png
    - assets/images/zodiac/icon_virgo/virgo.png
    # Chat
    - assets/images/chat/penhasAssistant/penhasAssistant.png
    - assets/images/chat/penhasContact/penhasContact.png
    # Support Center
    - assets/images/svg/support_center/list.svg
    - assets/images/svg/support_center/location.svg
    - assets/images/svg/support_center/suggest_place.svg
    - assets/images/svg/support_center/trace_route.svg
    - assets/images/support_center/map_marker/map_marker.png
    # Account
    - assets/images/svg/profile/edit.svg
    # Menu
    - assets/images/svg/drawer/menu_penhas_icone.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DesignSystemLogo
      fonts:
        - asset: assets/fonts/ds/DesignSystemLogo.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  icon: flutter pub run flutter_launcher_icons:main
  name: flutter pub run flutter_launcher_name:main
