name: penhas
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.7.1+68
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  asuka: ^2.0.1+3
  badges: ^2.0.2
  collection: ^1.16.0
  crypt: ^4.3.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  device_info_plus:
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_analytics: '9.3.1'
  firebase_core: '1.24.0'
  firebase_core_platform_interface: '4.5.1'
  firebase_crashlytics: '2.9.0'
  firebase_remote_config: ^2.0.20
  flutter_mobx: ^2.0.5
  flutter_modular: ^3.4.1+1
  flutter_phone_direct_caller: ^2.1.0
  flutter_secure_storage: ^6.1.0
  flutter_sound: ^9.2.13
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.3+1
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  http_parser: ^4.0.0
  intl: ^0.18.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  logging: ^1.0.2
  map_launcher: ^2.1.1
  mask_text_input_formatter: ^2.0.0
  meta: ^1.7.0
  mobx: ^2.0.5
  package_info_plus:
  path: ^1.8.0
  path_provider: ^2.0.8
  path_provider_android: ^2.0.22
  path_provider_ios: ^2.0.11
  permission_handler: ^8.3.0
  permission_handler_platform_interface: 3.7.0
  provider: ^6.0.1
  scroll_to_index: ^2.1.1
  shared_preferences: ^2.0.11
  shared_preferences_android: ^2.0.15
  shared_preferences_ios: ^2.1.1
  stack_trace: ^1.10.0
  synchronized: ^3.0.0+3
  timeago: ^3.1.0
  url_launcher: ^6.1.7
  uuid: ^3.0.5
  webview_flutter: ^3.0.0
  workmanager: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  alchemist: ^0.6.0 # snapshot test
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  flutter_modular_test: ^1.0.1
  freezed: ^2.0.4
  geolocator_platform_interface: ^4.0.3
  golden_toolkit: ^0.13.0 # snapshot test
  json_serializable: ^6.3.1
  lint: ^1.9.0
  mobx_codegen: ^2.0.4
  mocktail: ^1.0.0
  mocktail_image_network: ^1.2.0
  plugin_platform_interface: ^2.0.0

dependency_overrides:
  flutter_modular:
    git:
      url: https://github.com/pedrox-hs/modular.git
      path: flutter_modular
      ref: backward-compatibility
  flutter_modular_test:
    git:
      url: https://github.com/pedrox-hs/modular.git
      path: flutter_modular_test
      ref: backward-compatibility
  workmanager:
    git:
      url: https://github.com/pedrox-hs/flutter_workmanager.git
      ref: main

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/icon/icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/penhas_symbol/penhas_symbol.png
    - assets/images/stealth_mode_tutorial_image_1/stealth_mode_tutorial_image_1.png
    - assets/images/stealth_mode_tutorial_image_2/stealth_mode_tutorial_image_2.png
    - assets/images/stealth_mode_tutorial_image_3/stealth_mode_tutorial_image_3.jpg
    - assets/images/stealth_mode_tutorial_image_4/stealth_mode_tutorial_image_4.png
    - assets/images/svg/drawer/account_setting.svg
    - assets/images/svg/drawer/trash.svg
    - assets/images/svg/drawer/user_profile.svg
    - assets/images/svg/bottom_bar/chat.svg
    - assets/images/svg/bottom_bar/chat_selected.svg
    - assets/images/svg/bottom_bar/compose_tweet.svg
    - assets/images/svg/bottom_bar/compose_tweet_selected.svg
    - assets/images/svg/bottom_bar/emergency_controll.svg
    - assets/images/svg/bottom_bar/escape_manual.svg
    - assets/images/svg/bottom_bar/escape_manual_selected.svg
    - assets/images/svg/bottom_bar/feed.svg
    - assets/images/svg/bottom_bar/feed_selected.svg
    - assets/images/svg/bottom_bar/support_point.svg
    - assets/images/svg/bottom_bar/support_point_selected.svg
    - assets/images/svg/tweet_action/tweet_action_block.svg
    - assets/images/svg/tweet_action/tweet_action_chat.svg
    - assets/images/svg/tweet_action/tweet_action_delete.svg
    - assets/images/svg/tweet_action/tweet_action_report.svg
    - assets/images/svg/reset_password/recovery_password_step_1.svg
    - assets/images/svg/reset_password/recovery_password_step_2.svg
    - assets/images/svg/reset_password/recovery_password_step_3.svg
    - assets/images/svg/help_center/help_center_call_police.svg
    - assets/images/svg/help_center/help_center_guardian.svg
    - assets/images/svg/help_center/help_center_record.svg
    - assets/images/svg/tutorial/tutorial_guardian_01.svg
    - assets/images/tutorial_guardian_2/tutorial_guardian_2.png
    - assets/images/tutorial_guardian_3/tutorial_guardian_3.png
    - assets/images/tutorial_record_1/tutorial_record_1.png
    - assets/images/tutorial_record_2/tutorial_record_2.png
    - assets/images/tutorial_record_4/tutorial_record_4.png
    - assets/images/svg/help_center/guardians/guardians_delete.svg
    - assets/images/svg/help_center/guardians/guardians_edit.svg
    - assets/images/svg/help_center/guardians/guardians_sent_invite.svg
    - assets/images/svg/help_center/guardians/guardians_alert.svg
    # Actions
    - assets/images/svg/actions/delete.svg
    - assets/images/svg/actions/edit.svg
    - assets/images/svg/actions/close.svg
    # Zodiac
    - assets/images/zodiac/svg/constelation_aquarius.svg
    - assets/images/zodiac/svg/constelation_aries.svg
    - assets/images/zodiac/svg/constelation_cancer.svg
    - assets/images/zodiac/svg/constelation_capricorn.svg
    - assets/images/zodiac/svg/constelation_gemini.svg
    - assets/images/zodiac/svg/constelation_leo.svg
    - assets/images/zodiac/svg/constelation_libra.svg
    - assets/images/zodiac/svg/constelation_pisces.svg
    - assets/images/zodiac/svg/constelation_sagittarius.svg
    - assets/images/zodiac/svg/constelation_scorpio.svg
    - assets/images/zodiac/svg/constelation_taurus.svg
    - assets/images/zodiac/svg/constelation_virgo.svg
    - assets/images/zodiac/svg/moon.svg
    - assets/images/zodiac/svg/sun.svg
    - assets/images/zodiac/svg/venus.svg
    - assets/images/zodiac/icon_aquarius/aquarius.png
    - assets/images/zodiac/icon_aries/aries.png
    - assets/images/zodiac/icon_cancer/cancer.png
    - assets/images/zodiac/icon_capricorn/capricorn.png
    - assets/images/zodiac/icon_gemini/gemini.png
    - assets/images/zodiac/icon_leo/leo.png
    - assets/images/zodiac/icon_libra/libra.png
    - assets/images/zodiac/icon_pisces/pisces.png
    - assets/images/zodiac/icon_sagittarius/sagittarius.png
    - assets/images/zodiac/icon_scorpio/scorpio.png
    - assets/images/zodiac/icon_taurus/taurus.png
    - assets/images/zodiac/icon_virgo/virgo.png
    # Chat
    - assets/images/chat/penhasAssistant/penhasAssistant.png
    - assets/images/chat/penhasContact/penhasContact.png
    # Support Center
    - assets/images/svg/support_center/list.svg
    - assets/images/svg/support_center/location.svg
    - assets/images/svg/support_center/suggest_place.svg
    - assets/images/svg/support_center/trace_route.svg
    - assets/images/support_center/map_marker/map_marker.png
    # Account
    - assets/images/svg/profile/edit.svg
    # Menu
    - assets/images/svg/drawer/menu_penhas_icone.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DesignSystemLogo
      fonts:
        - asset: assets/fonts/ds/DesignSystemLogo.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/lato/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/lato/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/lato/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
