/// Flutter icons DesignSystemLogo
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DesignSystemLogo
///      fonts:
///       - asset: fonts/DesignSystemLogo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DesignSystemLogo {
  DesignSystemLogo._(); // coverage:ignore-line

  static const _kFontFam = 'DesignSystemLogo';

  static const IconData penhasLogo = IconData(0xe800, fontFamily: _kFontFam);
}
