source 'https://rubygems.org'

gem 'xcode-install'
gem 'cocoapods', '~> 1.11.3'
gem 'activesupport', '>= 6.1.7.1' # https://github.com/advisories/GHSA-j6gc-792m-qgm2

plugins_path = File.join(File.dirname(File.dirname(__FILE__)), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
