# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Ambiente Android do PenhaS"
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

  lane :android_beta_app do 
    firebase_app_distribution(
      firebase_cli_path: "/usr/local/bin/firebase",
      app: "1:51928851553:android:e8d613020f76da0b663620",
      release_notes_file: "../deploy/beta/release_notes",
      testers_file: "../deploy/beta/testers.android",
      apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
