# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$project_path = File.realpath(File.dirname(File.dirname(__FILE__)))

$app_name = 'PenhaS'
$api_base_url = ENV['PENHAS_BASE_URL']


private_lane :get_changelog do
  is_unreleased_section = false
  changelog_contents = ''
  File.readlines("#{$project_path}/CHANGELOG.md").each do |line|
    if is_unreleased_section
      if line.start_with?('## [')
        break
      end
      changelog_contents += line
    end

    is_unreleased_section = is_unreleased_section || line.start_with?('## [Unreleased]')
  end
  changelog_contents.strip
end
