# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Run code generators"
lane :pre_build do
  sh("flutter packages pub run build_runner build --delete-conflicting-outputs")
end

platform :android do

  desc "Build release APK"
  lane :build do
    pre_build
    sh("flutter build apk --release")
  end

  desc "Build release Bundle"
  lane :build_bundle do
    pre_build
    sh("flutter build appbundle --release")
  end

  desc "Distribute to Android beta testers"
  lane :distribute_android_beta do
    build
    firebase_app_distribution(
      app: "1:51928851553:android:fc14989f5670877f663620",
      release_notes_file: "./deploy/beta/release_notes",
      testers_file: "./deploy/beta/testers.android",
      groups: "androidtestersgroup",
      android_artifact_path: "./build/app/outputs/apk/release/app-release.apk"
    )
  end

end

platform :ios do

  desc "Build release IPA"
  lane :build do
    pre_build
    sh("flutter build ios --release --no-codesign")
  end

  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app
  end

  lane :update_profile do
    sigh(
      provisioning_name: "PenhaS AdHoc",
      force: true,
      adhoc: true,
      output_path: './ios/certificates'
    )
  end

  lane :sync_device_info do
    register_devices(
      devices_file: "./deploy/beta/device_file.ios"
    )
  end

  desc "Distribute to iOS beta testers"
  lane :distribute_iOS_beta do
    build
    sync_device_info
    update_profile

    gym(
      scheme: "Runner",
      archive_path: "./ios/build/Runner.xcarchive",
      export_method: "ad-hoc",
      output_directory: "./build/Runner"
    )

    firebase_app_distribution(
        app: "1:51928851553:ios:f741dab1c05cf04e663620",
        release_notes_file: "./deploy/beta/release_notes",
        testers_file: "./deploy/beta/testers.ios",
        groups: "iostestersgroup",
        ipa_path: "./build/Runner/Runner.ipa",
      #   debug: true
    )
  end
end
