name: penhas
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.1.1
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+1
  package_info: '>=0.4.0+16 <2.0.0'
  email_validator: ^1.0.4
  mask_text_input_formatter: ^1.0.6
  datetime_picker_formfield: ^1.0.0
  cpfcnpj: ^1.0.3
  url_launcher: ^5.4.7
  flutter_widget_from_html: ^0.4.1
  flutter_svg: ^0.17.4
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.0.0
  mobx: ^1.1.1
  provider: ^4.0.4
  timeago: ^2.0.26
  shared_preferences: ^0.5.6+3
  freezed: ^0.11.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/penhas_symbol/penhas_symbol.png
   - assets/images/reset_password_01/reset_password_01.png
   - assets/images/reset_password_02/reset_password_02.png
   - assets/images/stealth_mode_tutorial_image_1/stealth_mode_tutorial_image_1.png
   - assets/images/stealth_mode_tutorial_image_2/stealth_mode_tutorial_image_2.png
   - assets/images/stealth_mode_tutorial_image_3/stealth_mode_tutorial_image_3.png
   - assets/images/svg/drawer/account_setting.svg
   - assets/images/svg/drawer/trash.svg
   - assets/images/svg/drawer/user_profile.svg
   - assets/images/svg/bottom_bar/chat.svg
   - assets/images/svg/bottom_bar/chat_selected.svg
   - assets/images/svg/bottom_bar/compose_tweet.svg
   - assets/images/svg/bottom_bar/compose_tweet_selected.svg
   - assets/images/svg/bottom_bar/emergency_controll.svg
   - assets/images/svg/bottom_bar/feed.svg
   - assets/images/svg/bottom_bar/feed_selected.svg
   - assets/images/svg/bottom_bar/support_point.svg
   - assets/images/svg/bottom_bar/support_point_selected.svg
   - assets/images/svg/tweet_action/tweet_action_block.svg
   - assets/images/svg/tweet_action/tweet_action_chat.svg
   - assets/images/svg/tweet_action/tweet_action_delete.svg
   - assets/images/svg/tweet_action/tweet_action_report.svg

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DesignSystemLogo
      fonts:
        - asset: assets/fonts/ds/DesignSystemLogo.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          style: italic
          weight: 300

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
