name: penhas
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.13+13

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.1.1
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+1
  package_info: '>=0.4.0+16 <2.0.0'
  email_validator: ^1.0.4
  mask_text_input_formatter: ^1.0.6
  cpfcnpj: ^1.0.3
  url_launcher: ^5.4.7
  flutter_widget_from_html: ^0.4.1
  flutter_svg: ^0.18.0
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.0.0
  mobx: ^1.1.1
  provider: ^4.0.4
  timeago: ^2.0.26
  shared_preferences: ^0.5.6+3
  flutter_tags: ^0.4.8+2
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.3+3
  freezed_annotation: ^0.11.0
  permission_handler: ^5.0.1+1
  geolocator: ^5.3.2+2
  flutter_phone_direct_caller: ^1.0.1
  flutter_sound_lite: ^5.1.1
  uuid: ^2.2.0
  path: ^1.6.0
  path_provider: ^1.6.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  freezed: ^0.11.2

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/icon/icon.png'

flutter_launcher_name:
  name: 'PenhaS'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/penhas_symbol/penhas_symbol.png
    - assets/images/stealth_mode_tutorial_image_1/stealth_mode_tutorial_image_1.png
    - assets/images/stealth_mode_tutorial_image_2/stealth_mode_tutorial_image_2.png
    - assets/images/stealth_mode_tutorial_image_3/stealth_mode_tutorial_image_3.png
    - assets/images/svg/drawer/account_setting.svg
    - assets/images/svg/drawer/trash.svg
    - assets/images/svg/drawer/user_profile.svg
    - assets/images/svg/bottom_bar/chat.svg
    - assets/images/svg/bottom_bar/chat_selected.svg
    - assets/images/svg/bottom_bar/compose_tweet.svg
    - assets/images/svg/bottom_bar/compose_tweet_selected.svg
    - assets/images/svg/bottom_bar/emergency_controll.svg
    - assets/images/svg/bottom_bar/feed.svg
    - assets/images/svg/bottom_bar/feed_selected.svg
    - assets/images/svg/bottom_bar/support_point.svg
    - assets/images/svg/bottom_bar/support_point_selected.svg
    - assets/images/svg/tweet_action/tweet_action_block.svg
    - assets/images/svg/tweet_action/tweet_action_chat.svg
    - assets/images/svg/tweet_action/tweet_action_delete.svg
    - assets/images/svg/tweet_action/tweet_action_report.svg
    - assets/images/svg/reset_password/recovery_password_step_1.svg
    - assets/images/svg/reset_password/recovery_password_step_2.svg
    - assets/images/svg/reset_password/recovery_password_step_3.svg
    - assets/images/svg/help_center/help_center_call_police.svg
    - assets/images/svg/help_center/help_center_guardian.svg
    - assets/images/svg/help_center/help_center_record.svg
    - assets/images/svg/tutorial/tutorial_guardian_01.svg
    - assets/images/tutorial_guardian_2/tutorial_guardian_2.png
    - assets/images/tutorial_guardian_3/tutorial_guardian_3.png
    - assets/images/tutorial_record_1/tutorial_record_1.png
    - assets/images/tutorial_record_2/tutorial_record_2.png
    - assets/images/tutorial_record_3/tutorial_record_3.png
    - assets/images/tutorial_record_4/tutorial_record_4.png
    - assets/images/svg/help_center/guardians/guardians_delete.svg
    - assets/images/svg/help_center/guardians/guardians_edit.svg
    - assets/images/svg/help_center/guardians/guardians_sent_invite.svg
    - assets/images/svg/help_center/guardians/guardians_alert.svg
    # Zodiac
    - assets/images/zodiac/svg/constelation_aquarius.svg
    - assets/images/zodiac/svg/constelation_aries.svg
    - assets/images/zodiac/svg/constelation_cancer.svg
    - assets/images/zodiac/svg/constelation_capricorn.svg
    - assets/images/zodiac/svg/constelation_gemini.svg
    - assets/images/zodiac/svg/constelation_leo.svg
    - assets/images/zodiac/svg/constelation_libra.svg
    - assets/images/zodiac/svg/constelation_pisces.svg
    - assets/images/zodiac/svg/constelation_sagittarius.svg
    - assets/images/zodiac/svg/constelation_scorpio.svg
    - assets/images/zodiac/svg/constelation_taurus.svg
    - assets/images/zodiac/svg/constelation_virgo.svg
    - assets/images/zodiac/svg/moon.svg
    - assets/images/zodiac/svg/sun.svg
    - assets/images/zodiac/svg/venus.svg
    - assets/images/zodiac/icon_aquarius/aquarius.png
    - assets/images/zodiac/icon_aries/aries.png
    - assets/images/zodiac/icon_cancer/cancer.png
    - assets/images/zodiac/icon_capricorn/capricorn.png
    - assets/images/zodiac/icon_gemini/gemini.png
    - assets/images/zodiac/icon_leo/leo.png
    - assets/images/zodiac/icon_libra/libra.png
    - assets/images/zodiac/icon_pisces/pisces.png
    - assets/images/zodiac/icon_sagittarius/sagittarius.png
    - assets/images/zodiac/icon_scorpio/scorpio.png
    - assets/images/zodiac/icon_taurus/taurus.png
    - assets/images/zodiac/icon_virgo/virgo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DesignSystemLogo
      fonts:
        - asset: assets/fonts/ds/DesignSystemLogo.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  icon: flutter pub run flutter_launcher_icons:main
  name: flutter pub run flutter_launcher_name:main

