#!/bin/bash

set -e

PROJECT_DIR=$(dirname $(dirname `realpath ${BASH_SOURCE[0]}`))

cd $PROJECT_DIR

bundle exec fastlane android firebase_distribute --verbose
bundle exec fastlane ios     firebase_distribute --verbose
