#!/bin/bash

set -e

PROJECT_DIR=$(dirname $(dirname `realpath ${BASH_SOURCE[0]}`))

cd $PROJECT_DIR

bundle exec fastlane android distribute_android_beta --verbose
#fastlane ios distribute_iOS_beta --verbose
