---
name: Leaked Secrets Scan
on:
  - pull_request

jobs:
  TruffleHog:
    runs-on: ubuntu-latest

    # Restrict permissions for GITHUB_TOKEN
    permissions:
      contents: read  # Only allow reading the repository contents
      pull-requests: read  # Only allow reading pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
