name: "Distribute app"

on:
  workflow_call:
    inputs:
      platform:
        description: "Build target platform"
        type: string
        required: true
      environment:
        description: "Distribution environment"
        type: string
        required: true

    secrets:
      PENHAS_BASE_URL:
        required: true
      ANDROID_BUILD_FILES:
        required: true
      APPLE_ID:
        required: true
      IOS_BUILD_FILES:
        required: true
      FIREBASE_TOKEN:
        required: false
      APPLE_API_KEY_B64:
        required: true
      GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64:
        required: false
      TESTER_EMAIL:
        required: false

jobs:
  distribute:
    needs: pre-distribute
    strategy:
      matrix: ${{ fromJSON(needs.pre-distribute.outputs.matrix) }}
    runs-on: ${{ matrix.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Setup Java
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        if: ${{ matrix.platform == 'android' }}
        uses: android-actions/setup-android@v2

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Get config files for Android
        if: ${{ matrix.platform == 'android' }}
        run: |
          base64 -d <<< "${{ secrets.ANDROID_BUILD_FILES }}" | tar xzf -
          base64 -d <<< "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64 }}" > ${{ matrix.working-directory }}/play-store-api-key.json

      - name: Get config files for iOS
        if: ${{ matrix.platform == 'ios' }}
        run: |
          base64 -d <<< "${{ secrets.IOS_BUILD_FILES }}" | tar xzf -
          base64 -d <<< "${{ secrets.APPLE_API_KEY_B64 }}" > ${{ matrix.working-directory }}/app-store-api-key.json
          sudo xcode-select -s /Applications/Xcode_14.2.app

      - name: Install Ruby to use Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ${{ matrix.working-directory }}

      - name: Run lane to distribute
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ vars.TARGET_LANE }}
          options: '{ "tester_email": "${{ secrets.TESTER_EMAIL }}" }'
          subdirectory: ${{ matrix.working-directory }}
        env:
          PENHAS_BASE_URL: ${{ secrets.PENHAS_BASE_URL }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          IOS_BUNDLE_ID: ${{ vars.IOS_BUNDLE_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_SKIP_UPDATE_CHECK: true

  pre-distribute:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.definition.outputs.matrix }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      PLATFORM: ${{ inputs.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - id: definition
        name: "Prepare distribution"
        run: |
          yaml2json() {
            python -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin.read())))'
          }

          JQ_EXPR=$(cat <<EOF
            del( .[] | select(.platform != "$PLATFORM" and "$PLATFORM" != "all"))
          EOF
          )
          MATRIX="{ \"include\": $(yaml2json < .github/distribute-platforms.yml | jq -Mc "$JQ_EXPR") }"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
