name: "Manual app distribution"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - android
          - ios
          - all
        type: choice
        required: true
      environment:
        description: "Distribution environment"
        type: environment
        required: true

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      platform: ${{ github.event.inputs.platform }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      PENHAS_BASE_URL: ${{ secrets.BASE_URL }}
      BUILD_CONFIG_FILES: ${{ secrets.BUILD_CONFIG_FILES }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      TARGET_LANE: ${{ secrets.TARGET_LANE }}
