name: "Manual app distribution"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - android
          - ios
          - all
        type: choice
        required: true
      environment:
        description: "Distribution environment"
        type: environment
        required: true

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      platform: ${{ github.event.inputs.platform }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      PENHAS_BASE_URL: ${{ secrets.PENHAS_BASE_URL }}
      APPLE_API_KEY_B64: ${{ secrets.APPLE_API_KEY_B64 }}
      GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64 }}
      ANDROID_BUILD_FILES: ${{ secrets.ANDROID_BUILD_FILES }}
      IOS_BUILD_FILES: ${{ secrets.IOS_BUILD_FILES }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
