name: "Distribute app to tester"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - all
          - android
          - ios
        type: choice
        required: true
      tester_email:
        description: "Tester email address"
        type: string
        required: true

jobs:

  distribute-android:
    if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
    uses: ./.github/workflows/distribute-flutter-android.yml
    with:
      environment: firebase-distribution
    secrets:
      ANDROID_BUILD_FILES: ${{ secrets.ANDROID_BUILD_FILES }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64 }}
      PENHAS_BASE_URL: ${{ secrets.PENHAS_BASE_URL }}
      TESTER_EMAIL: ${{ github.event.inputs.tester_email }}

  distribute-ios:
    if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
    uses: ./.github/workflows/distribute-flutter-ios.yml
    with:
      environment: firebase-distribution
    secrets:
      APPLE_API_KEY_B64: ${{ secrets.APPLE_API_KEY_B64 }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      CERTIFICATE_CONTENT: ${{ secrets.CERTIFICATE_CONTENT }}
      CERTIFICATE_PWD: ${{ secrets.CERTIFICATE_PWD }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      IOS_BUILD_FILES: ${{ secrets.IOS_BUILD_FILES }}
      PENHAS_BASE_URL: ${{ secrets.PENHAS_BASE_URL }}
      TESTER_EMAIL: ${{ github.event.inputs.tester_email }}
